### ISSUE TITLE
How i compile it SFML with VS2019?

### ISSUE THREAD

**Issue by Deltwin** [xhz8s/pHake#10]
I download SFML from your README.md i extracted it to > C:\Libraries\SFML.version.x\
But now? How i can compile it?

**Comment by xhz8s** [comment]
You need to compile the code as x64 Release, Debug is broken right now

**Comment by xhz8s** [comment]
Debug is fixed now btw

**Comment by Deltwin** [comment]
Yeah but how? If i go to vs2019 > File > Open Folder and i select SFML > Debug > Compile it gives me error..

**Comment by xhz8s** [comment]
You need to open the source as a project, so File->Open->Project/Solution -> choose pHake.sln and then compile

**Comment by Deltwin** [comment]
it gives me so many error wait.. i will show what i did

1. I downloaded SFML from your github 
2. I put it in C:\Libraries\SMFL-version.x
3. I go to vs2019 > open project > compile > it gimes me 114 errors...
4. wtf

**Comment by Deltwin** [comment]
https://user-images.githubusercontent.com/42442148/102546130-76b99a00-40b7-11eb-8cac-73fbc2eb94e1.mp4

**Comment by xhz8s** [comment]
download the cheat again and try compiling it again
