### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by MirzaGorgAli** [xhz8s/pHake#12]
Hi @xhz8s thank you for this awesome project .
I have two questions:
Can I use this cheat for FIVEM ?
And You will update this source if it needs (I mean Offsets)?
If not Can You tell me how to find offsets?
THANKS
*SORRY ABOUT MY ENGLISH*

**Comment by xhz8s** [comment]
This is a GTA Online only cheat. If you want to learn how to reverse games and write cheats start here https://guidedhacking.com/
