### ISSUE TITLE
Memory error?

### ISSUE THREAD

**Issue by dqvist12** [xhz8s/pHake#15]
I get an error "Unhandled exception at 0x00007FFBEBCFD759 in pHake.exe: Microsoft C++ exception: std::length_error at memory location" when i try to debug. . .

**Comment by xhz8s** [comment]
Can you provide more Information ? Like in which mode you compiled etc...

**Comment by dqvist12** [comment]
I think I have succeeded to solve the memory problem. However when I run the trainer no text description is visible, here is a pic https://i.imgur.com/g9gppLh.png. Really good trainer by the way 👍

**Comment by xhz8s** [comment]
Ah yes, that's an easy fix! You just need to have "Release/font.ttf" in your executable folder, just like in the latest release. You can download the font [here](https://github.com/xhz8s/pHake/releases/download/0/dp.zip)
