### ISSUE TITLE
Triggerbot does not work with some weapons

### ISSUE THREAD

**Issue by abobainc** [xhz8s/pHake#24]
It doesn't work with heavy sniper mk.2 (explosive ammo), idk about other but pretty sure that they dont work too
Please make it work especially it will be good if triggerbot will work with vehicles (jets and heli, maybe other)

**Comment by xhz8s** [comment]
https://github.com/xhz8s/pHake/commit/08eea0097d6ef71a1ccec79766c759bea0be3539

now works with all weapons, will be included in next update
