### ISSUE TITLE
Would that work in linux?

### ISSUE THREAD

**Issue by otuva** [xhz8s/pHake#27]
I might try with protontricks and let you know if it works or not but have you tried it yourself?

**Comment by xhz8s** [comment]
I have not, but someone on uc said that everything works except the ui

**Comment by otuva** [comment]
Do you know the steps to make it work?

**Comment by xhz8s** [comment]
nope

**Comment by otuva** [comment]
I was able to get it running under same wine prefix with steamtinkerlaunch and custom command injection [like this](https://github.com/frostworx/steamtinkerlaunch/wiki/Custom-Program) but as you mentioned gui is completely broken. When injected it blocks all other windows and has to be closed.

I heavily modified it by deleting gui completely and mapped all of the functions to hotkeys then compiled it under a VM and it was working fine. But the whole process was painful besides gui is kind of a necessity in this type of programs.

I think it's completely waste of time trying to get windows hacks working under linux. If anything it should be native build.
Wine does not scramble ram locations though so all offsets were working right away

I might decide to write a native menu using gdb to attach to the process but I'm dual booting anyway and it's such a hassle.

Thanks for this decent cheat menu
