### ISSUE TITLE
Black screen on Linux when injected

### ISSUE THREAD

**Issue by otuva** [xhz8s/pHake#32]
Hi, after injection, menu overlay rectangle blocks everything including audio from every process. I don't know about SFML enough to debug it but, here are things I've tried:

- Link SFML libraries statically rather than dynamically 
- Limit black rectangle height and width

By the way, you cannot toggle menu after the glitch.

![Screenshot from 2022-12-30 22-34-14](https://user-images.githubusercontent.com/67955086/210106658-c1f5d007-30fd-4a6e-b6ac-060cbcfc0c77.png)

**Comment by xhz8s** [comment]
1. the cheat is currently not in a working condition.
 2. The GUI works perfectly on native Windows, it is Proton's/Wine's task to translate correctly.

**Comment by otuva** [comment]
1- As you can see, I've compiled the latest commit version. God mode etc. is working fine
2- You don't say :) The thing is, as you know, SFML is a cross-platform library, and even more complex projects than this work on proton. Now, before opening this issue I've tested both SFML and SDL to show a transparent rectangle with injected processes, and they worked without a hitch. As I said, currently I don't know enough about SFML and my uneducated guess would be this is happening because the project uses a kind of windows native "hack" hence the reason for this issue.

**Comment by xhz8s** [comment]
1. Ya but things like BoostPlayer etc are missing. The same reason why the menu toggle isn't working
2. Try playing around with pOverlay::SetWindowTransparentAndNotClickableEx. Had to do really hacky things in order to get sfml "cheat ready". But you could also use pWindow instead of pOverlay. It's the standalone window version of pOverlay

**Comment by xhz8s** [comment]
Inactive
