### ISSUE TITLE
Searching peds

### ISSUE THREAD

**Issue by CoderzNation** [xhz8s/pHake#4]
How exactly did you find the list of peds? and how can I individually analyze each ped properties?

**Comment by xhz8s** [comment]
I found it by searching for the address that holds the pointer to the nearest ped. You can use ReClass or Cheat Engines built in structure tool

**Comment by CoderzNation** [comment]
Nice. I just built a function that kills all pedestrians around you every millisecond. We should create some ped definition file because right now It's basically writing to each pedestrian using mem.write. It'd be nice if we cleaned it up

**Comment by xhz8s** [comment]
A skimmed down version of [LocalPlayer.hpp](https://github.com/xhz8s/pHake/blob/master/pHake/SDK/LocalPlayer.hpp) would be enough I guess
